### ISSUE TITLE
Create basic emotion detection model

### ISSUE THREAD

**Issue by dharmik2319** [Reaper-1709/Showcasing-2024-25-SPS#2]
No progress as of now, needs work

**Comment by Reaper-1709** [comment]
Please send any tutorial link which providesa way to make a machine learning model which is accurate enough for the purpose.

**Comment by dharmik2319** [comment]
yeah sorry for being late, was a bit short on space. will install the required libs and do it soon

**Comment by dharmik2319** [comment]
done
